server:
  port: 9091 #端口
  # 应用名称
spring:
  application:
    name: service-consumer
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yang_zzu?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  #配置
  # 主机名
eureka:
  instance:
    hostname: service-consumer-cloud
    prefer-ip-address: true # 是否使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    register-with-eureka: true # 是否将自己注册到 注册中心， 默认为true
    fetch-registry: true # 从注册中心获取服务注册信息， 默认为true
    registry-fetch-interval-seconds: 30 #Eureka clint 去服务器拉取注册信息，默认为30s
    service-url:
      defaultZone: http://root:123456@localhost:8760/eureka/,http://root:123456@localhost:8761/eureka/,http://root:123456@localhost:8762/eureka/
#       defaultZone: http://localhost:8760/eureka/,http://localhost:8761/eureka/,http://localhost:8762/eureka/

# 度量指标监控 与 健康检查
management:
  endpoints:
    web:
      exposure:
        include: shutdown # 开启 shutdown 端点访问
  endpoint:
    shutdown:
      enabled: true # 开启 shutdown 实现优雅停服


# Ribbon 负载均衡策略
service-provider: # 指定策略的服务名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #轮询策略（默认）
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #随机策略
#    listOfServers: http://localhost:7071,http://localhost:7072 # 指定ribbon 直连的地址

# 关闭 eureka 使用 ribbon 点对点直连
#ribbon:
#  eureka:
#    enabled: false # false 关闭， true 开启

# 提供服务的服务名称
yang:
  provide:
    name: service-provider

