server:
  port: 8890 #端口

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850  # nacos服务器地址
        namespace: 5129a7bf-a75e-4b17-9f17-36b252547732  #命名空间
        group: NACOS_PROVIDER #群组
        ephemeral: false   #false为永久实例，true表示临时实例开启，注册为临时实例

# Ribbon 负载均衡策略
service-provider: # 指定策略的服务名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #轮询策略（默认）
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #随机策略
#    listOfServers: http://localhost:7071,http://localhost:7072 # 指定ribbon 直连的地址

yang:
  provide:
    name: nacos-provider